targets = []

# More documentation for the advisories section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/advisories/cfg.html
[advisories]
db-path = "./.tools/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"
ignore = []

# * None - CVSS Score 0.0
# * Low - CVSS Score 0.1 - 3.9
# * Medium - CVSS Score 4.0 - 6.9
# * High - CVSS Score 7.0 - 8.9
# * Critical - CVSS Score 9.0 - 10.0
severity-threshold = "Low"

# More documentation for the licenses section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html
[licenses]
unlicensed = "deny"
allow = [
    "Apache-2.0",
    #"BSD-3-Clause",
    "ISC",
    "MIT",
    "OpenSSL",
    "Unicode-DFS-2016",
]
deny = []

copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.8
exceptions = [
    #{ allow = ["Zlib"], name = "adler32", version = "*" },
]

[licenses.private]
ignore = false
registries = []

# More documentation about the 'bans' section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/bans/cfg.html
[bans]
multiple-versions = "warn"
wildcards = "warn"
highlight = "all"
allow = []
deny = []
skip = [
    { name = "syn", version = "1.0.109" },
    { name = "windows-sys", version = "0.45.0" },
    { name = "windows-targets", version = "0.42.2" },
    { name = "windows_aarch64_gnullvm", version = "0.42.2" },
    { name = "windows_aarch64_msvc", version = "0.42.2" },
    { name = "windows_i686_gnu", version = "0.42.2" },
    { name = "windows_i686_msvc", version = "0.42.2" },
    { name = "windows_x86_64_gnu", version = "0.42.2" },
    { name = "windows_x86_64_gnullvm", version = "0.42.2" },
    { name = "windows_x86_64_msvc", version = "0.42.2" },
]
skip-tree = []

# More documentation about the 'sources' section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/sources/cfg.html
[sources]
unknown-registry = "deny"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = []
gitlab = []
bitbucket = []

# License fixes for known issues
[[licenses.clarify]]
name = "ring" # v0.16.20
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]
