edition = "2021"
version = "Two"
unstable_features = true

blank_lines_lower_bound = 0
blank_lines_upper_bound = 2

comment_width = 80
normalize_comments = false
normalize_doc_attributes = true
wrap_comments = true

hard_tabs = false
indent_style = "Block"
newline_style = "Unix"
tab_spaces = 4

binop_separator = "Front"
brace_style = "SameLineWhere"
# combine_control_expr = false
condense_wildcard_suffixes = false
control_brace_style="ClosingNextLine"
empty_item_single_line = true
fn_params_layout = "Tall"
fn_single_line = true
force_explicit_abi = true
force_multiline_blocks = true
match_arm_blocks = true
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
overflow_delimited_expr = false
remove_nested_parens = true
reorder_impl_items = true
trailing_comma = "Vertical"
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = false

enum_discrim_align_threshold = 30
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 40

format_code_in_doc_comments = true
format_macro_matchers = false
format_macro_bodies = true
format_strings = true

imports_indent = "Block"
imports_layout = "Vertical"
imports_granularity = "Crate"
inline_attribute_width=0
merge_derives = true

group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

